### ISSUE TITLE
wrong Bootloader Version in configurator

### ISSUE THREAD

**Issue by TheIsotopes** [am32-firmware/AM32-bootloader#15]
Is it normal that with latest bootloader v12 / firmware v2.16 the bootloader version 1 is displayed instead of version 12?

![Screenshot 2024-09-13 124519](https://github.com/user-attachments/assets/3ae7ed03-ffb2-41c8-984c-d5d80c49f736)

**Comment by tridge** [comment]
how did you load the bootloader?

**Comment by tridge** [comment]
i've found the issue, and fixed in #18, thanks for reporting this!
